server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=library_management
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: library_management
  liquibase:
    default-schema: library_management
    liquibase-schema: library_management
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml


security:
  auth:
    whitelist: >
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**,
      /v3/api-docs/**,
      /v3/api-docs,
      /swagger-ui/**,
      /v2/api-docs,
      /api/admins,
      /api
